<?php

$ausgabe['titel'] = 'Veranstaltung Hinzufügen';
include TEMPLATES . 'htmlkopf.phtml';

?>
<form action="<?= $_SERVER['PHP_SELF'] ?>" method="post">
<input type="hidden" name="vid" id="vid" value="<?= $form['vid'] ?>">

    <?php

    $ausgabe['beschriftung'] = 'Veranstaltung';
    $ausgabe['feldname'] = 'name';
    $ausgabe['typ'] = 'text';
    $ausgabe['cssklasse'] = 'pflicht';
    include TEMPLATES . 'inputfeld.phtml';
    ?>
    
<!--        Ort als Selectbox-->
    <div>
                <label for="oid">Ort</label>
                <select name="oid" id="oid">
                    <option value="" label="Ort auswählen"></option>
                    <?php foreach($orte as $key => $value): ?>
                    <option value="<?= $key ?>" <?= $key == $form['oid'] ? 'selected' : '' ?>><?= $value ?></option>
                    <?php endforeach; ?>
                </select>
               
            </div>
<?php
    $ausgabe['beschriftung'] = 'Veranstaltungstag';
    $ausgabe['feldname'] = 'datum';
    $ausgabe['typ'] = 'date';
    $ausgabe['cssklasse'] = 'pflicht';
    include TEMPLATES . 'inputfeld.phtml';
    
    // Beschreibung bitte nach unten fuer die Aesthetik!
    ?>
    <div>
        <label for="beschreibung">Beschreibung</label>
        <textarea name="beschreibung" id="beschreibung"><?= htmlspecialchars($form['beschreibung']) ?></textarea>
        <span><?= $fehler['beschreibung'] ?? '' ?></span>
    </div>


    <div>
        <button type="submit" name="okbutton" value="1">speichern</button>
    </div>

            <div class='formcaption'>Felder in <span class='pflicht'>blau</span> sind Pflichtfelder</div>
            </form>
    <?php
    include TEMPLATES . 'htmlfuss.phtml';
    