<?php
// Seitentitel festlegen
$ausgabe['titel'] = 'Ändern';
include TEMPLATES . 'htmlkopf.phtml';
?>
<?php if (!empty($fehler['vid'])): ?>
    <h3><span><?= $fehler['vid'] ?></span></h3>
    <h4><a href="pindexadmin.php">zurück zur Übersicht</a></h4>
<?php else: ?>
    <form action="<?= $_SERVER['PHP_SELF'] ?>" method="post">
        <input type="hidden" name="vid" id="vid" value="<?= $form['vid'] ?>">

        <?php
        $ausgabe['feldname'] = 'name';
        $ausgabe['beschriftung'] = 'Veranstaltung';
        $ausgabe['typ'] = 'text';
        $ausgabe['cssklasse'] = 'pflicht';
        include TEMPLATES . 'inputfeld.phtml';
        ?>

        <!--        Ort als Selectbox-->
        <div>
            <label for="oid">Ort</label>
            <select name="oid" id="oid">
                <option value="" label="Ort auswählen"></option>
                <?php foreach ($orte as $key => $value): ?>
                    <option value="<?= $key ?>" <?= $key == $form['oid'] ? 'selected' : '' ?>><?= $value ?></option>
                <?php endforeach; ?>
            </select>
        </div>


        <?php
        $ausgabe['feldname'] = 'datum';
        $ausgabe['beschriftung'] = 'Veranstaltungstag';
        $ausgabe['typ'] = 'date';
        $ausgabe['cssklasse'] = 'pflicht';
        include TEMPLATES . 'inputfeld.phtml';
        ?>
        <div>
            <label for="beschreibung">Beschreibung</label>
            <textarea name="beschreibung" id="beschreibung"><?= $form['beschreibung'] ?></textarea>
            <span><?= $ergebnis['beschreibung'] ?? '' ?></span>
        </div>
        <div>
            <button type="submit" name="okbutton" value="1">speichern</button>
          
        </div>  
       
        <div class='formcaption'>Felder in <span class='pflicht'>blau</span> sind Pflichtfelder</div>
     </form>
<?php endif; ?>
<?php
include TEMPLATES . 'htmlfuss.phtml';
