<?php
/*
 * Template für die leuchtende Spalten
 * 
 * Benötigte Variablen:
 * 
 * $ausgabe['spaltenanzahl']
 */

?>
                    <colgroup>
                          <?php 
                          for($i = 1; $i <= $ausgabe['spaltenanzahl']; $i++):
                        ?>
                          <col>
                          
                          <?php
                          endfor;
                          ?>
                    </colgroup>