<?php
/**
 * Tabellen Template, anpassbar
 * 
 * $ausgabe['titel'] = Name der HTML Ueberschrift, in ""
 * $ausgabe['spaltenzahl'] = Anzahl der Spalten
 * $ausgabe['admin'] =   1 = + bearbeiten und loeschen buttons, bitte Spaltenzahl bedenken 0 = Besucher Ansicht
 */
include TEMPLATES . 'htmlkopf.phtml';
?>

<!--Die Anzahl der gefundenen Datensatze ausgeben-->
<h3><?= number_format($anzahl, 0, ',', '.') ?> Veranstaltungen gefunden</h3>


<?php include TEMPLATES . 'paginator.phtml'; ?>
<table>

    <?php
    include TEMPLATES . 'spaltenanzahl.phtml';
    ?>

    <tr>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=vid">ID</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=name">Name</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=ort">Ort</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=plz">PLZ</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=datum">Datum</a></th>
        <!--        Abfrage für den Fall, dass der Adminbereich aufgerufen wird-->
        <?php if ($ausgabe['admin']): ?>
            <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=beschreibung">Beschreibung</a></th>
        <?php endif; ?>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=adresse">Adresse</a></th>
        <th><a href="<?= $_SERVER['PHP_SELF'] ?>?sort=stadt">Stadt</a></th>
        <!--        Ausnahme für den Fall, dass der Adminbereich aufgerufen wird-->
        <?php if ($ausgabe['admin']): ?>
            <th> &nbsp; </th>
            <th> &nbsp; </th>
        <?php endif; ?> 
    </tr>
<!--               Normale Schleifen mit Ausnahme, damit die Namen klickbar werden-->
    <?php foreach ($veranstaltungen as $veranstaltung): ?>
        <tr>
            <?php foreach ($veranstaltung as $key => $value): ?>
            
                <?php if ($key == 'name'): ?>
                    <td><a href="veranstaltung_details.php?detailsid=<?= $veranstaltung['vid'] ?>"><?= $value ?></a></td>
                <?php else: ?>
                    <td><?= $value ?></td>
                <?php endif; ?>
            <?php endforeach; ?>    
            <!--        Ausnahme für den Fall, dass der Adminbereich aufgerufen wird-->
            <?php if ($ausgabe['admin']): ?>
                <td><a href="veranstaltung_aendern.php?updateid=<?= $veranstaltung['vid'] ?>">bearbeiten</a></td>
                <td><a href="veranstaltung_loeschen.php?loeschid=<?= $veranstaltung['vid'] ?>">löschen</a></td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
</table>
<div>

    <form action="<?= $_SERVER['PHP_SELF'] ?>" name="suche" method="get">
        <h3>Suche</h3>
<!--        Suche nach Name UND Beschreibung-->
        <label for="name">Name oder Inhalt</label>
        <input type="text" class="name" name="name" id="name" value="<?= $suchstring_name ?>">

        <label for="ort">Ort</label>
        <input type="text" name="ort" id="ort" value="<?= $suchstring_ort ?>">

        <label for="plz_von">PLZ von</label>
        <input type="text" name="plz_von" id="plz_von" value="<?= $suchstring_plz_von ?>">

        <label for="plz_bis">PLZ bis</label>
        <input type="text" name="plz_bis" id="plz_bis" value="<?= $suchstring_plz_bis ?>">

        <label for="datum">Datum</label>
        <input type="date" name="datum" id="datum" value="<?= $suchstring_datum ?>">

        <div class="okknopf">  
            <button type="submit" class="okknopf">suchen</button>
        </div>
    </form>
</div>
<?php
include TEMPLATES . 'htmlfuss.phtml';
